$(document).ready(function(){
  $(".hide1").click(function(){
    $(".firstbox").css("visibility","hidden");
  });
  $(".hide2").click(function(){
    $(".secondbox").css("visibility","hidden");
  });
  $(".hide3").click(function(){
    $(".thirdbox").css("visibility","hidden");
  });
  $(".hide4").click(function(){
    $(".firstbox").css("visibility","hidden");
    $(".secondbox").css("visibility","hidden");
    $(".thirdbox").css("visibility","hidden");
  });
  $(".showall").click(function(){
    $(".firstbox").css("visibility","visible");
    $(".secondbox").css("visibility","visible");
    $(".thirdbox").css("visibility","visible");
});
  $(".change1").click(function(){
      $(".firstbox").css("background-color","blue");
      $(".firstbox").css("border-color","green");
    })
    $(".change2").click(function(){
      $(".secondbox").css("background-color","yellow");
      $(".secondbox").css("border-color","purple");
    })
    $(".change3").click(function(){
      $(".thirdbox").css("background-color","pink");
      $(".thirdbox").css("border-color","red");
    })
    $(".change4").click(function(){
      $(".firstbox").css("background-color","purple");
      $(".firstbox").css("border-color","yellow");
      $(".secondbox").css("background-color","gray");
      $(".secondbox").css("border-color","blue");
      $(".thirdbox").css("background-color","orange");
      $(".thirdbox").css("border-color","lightblue");
    })
    $(".reset").click(function(){
      $(".firstbox").css("background-color","red");
      $(".firstbox").css("border-color","black");
      $(".secondbox").css("background-color","blue");
      $(".secondbox").css("border-color","yellow");
      $(".thirdbox").css("background-color","RGB(73, 251, 53)");
      $(".thirdbox").css("border-color","pink");
      })

});